---
- name: Update lab environment using dnf module
  remote_user: jessdakota
  hosts: all
  become: true

  tasks:
    - name: Update packages on all RHEL systems using the dnf module
      when: ansible_os_family == "RedHat"
      ansible.builtin.dnf:
        name: '*'
        state: latest
