---
- name: Update lab environment using dnf module
  remote_user: jessdakota
  hosts: all
  become: true

  tasks:
    - name: Update packages on all RHEL systems using the dnf module
      when: ansible_os_family == "RedHat"
      ansible.builtin.package:
        name: '*'
        state: latest

    -name: Update packages on rhel systems using the yum module
    