---
- name: Update lab environment Insights information
  remote_user: jessdakota
  hosts: all
  become: true

  tasks:
    - name: Check in with Red Hat Insights services
      community.general.redhat_ insights:
        state: enabled
      register: insights
