---
- name: Update lab environment using package module
  remote_user: jessdakota
  hosts: all
  become: true

  tasks:
    - name: Update packages on all RHEL systems
      ansible.builtin.package:
        name: '*'
        state: latest

    
    

    