---
- name: Install enable and apply SNMP configuration to RHEL hosts
  hosts: all
  become: true

  tasks:
    - name: Install snmp packages on RHEL system
      ansible.builtin.package:
        name:
          - net-snmp
          - net-snmp-utils
        state: latest

    - name: Enable snmp service on RHEL systems
      ansible.builtin.service:
        name: snmpd
        enabled: true
        state: started

    - name: Modify snmpd.conf file replacing 'public' with 'h3Alth!x.snmpRO'
      ansible.builtin.lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: public
        line: h3Alth!x.snmpRO
        backrefs: true