---
- name: Install enable and apply SNMP configuration to RHEL hosts
  hosts: all
  become: true

  tasks:
    - name: Install snmp packages on RHEL system
      ansible.builtin.package:
        name:
          - net-snmp
          - net-snmp-utils
        state: latest

    - name: Start snmpd service on RHEL systems
      ansible.builtin.service:
        name: snmpd
        enabled: true
        state: started

    - name: Modify snmpd.conf file commenting the default 'public' entry 
      ansible.builtin.lineinfile:
        path: /etc/snmp/snmpd.conf
        regexp: 'com2sec notConfigUser  default       public'
        line: '#com2sec notConfigUser  default       public'
        backrefs: true

    - name: Modify snmpd.conf file adding SNMP ro community
      ansible.builtin.lineinfile:
        path: /etc/snmp/snmpd.conf
        line: 'rwcommunity PASSWORD'
        state: present
        create: true
    
    - name: Modify snmpd.conf file adding SNMP rw community
      ansible.builtin.lineinfile:
        path: /etc/snmp/snmpd.conf
        line: 'rwcommunity  PASSWORD'
        state: present
        create: true
    
    - name: Restart snmp service on RHEL systems
      ansible.builtin.service:
        name: snmpd
        state: restarted
        enabled: true
