---

- name: Create VMs
  hosts: ender.jmacmini.lab
  vars:
      vm_name: demo
      vm_memory: 4096
      vm_vcpus: 4
      vm_disk: 100GB
  roles:
      - role: stackhpc.libvirt-vm
        libvirt_vms:
         - state: present
           name: '{{vm_name}}'
           memory_mb: '{{vm_memory}}'
           vcpus: '{{vm_vcpus}}'
           volumes:
             - name: 'data2'
               device: 'disk'
               format: 'qcow2'
               capacity: '{{vm_disk}}'
               pool: 'vm-images'
