---
- name: Create VMs
  hosts: hypervisor
  vars: 
      vm_name: testvm
      vm_memory: 1024
      vm_disk: 200GB

      
  roles:
    - role: stackhpc.libvirt-vm
      libvirt_vms:
       - state: present
          name: { vm_name }
          memory_mb: { vm_memory }
          vcpus: 1
          volumes:
            - name: 'data2'
              device: 'disk'
              format: 'qcow2'
              capacity: 'vm_disk'
              pool: 'my-pool'