---
- name: update lab environment using package module
  remote_user: jessdakota
  become: yes

  tasks:
  - name: Update packages on all RHEL systems
    ansible.builtin.package:
      name: '*'
      state: latest






